feat: bottom bar
mserwo/sample-app pull request #2
Opened 2024-01-25 21:55 UTC by mserwo

2024-01-25 21:56 UTC, GabrLit commented
comment

2024-01-25 21:57 UTC, mserwo commented on src/pages/home/home.tsx
>        <div>home</div>
super!

2024-01-25 21:58 UTC, GabrLit commented on src/pages/home/home.tsx
> +      <div>tu jest mój rodzic</div>
to be deleted, unnecessary

2024-01-29 19:59 UTC, GabrLit requested changes

2024-01-29 19:59 UTC, GabrLit commented on src/components/footer/bottom-bar.tsx
> +        <div className={styles.bottomBar_rightFrame}>
frame would be bad naming here. Iframe in web development refers to a specific object: 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe

2024-01-29 19:59 UTC, GabrLit commented on src/components/footer/footer.module.scss
> +  @include fonts.poppins;
what is this include here, include should be at the top if anything? and as far as I remember we do have a font family already specified somewhere in global scss file?

2024-01-29 19:59 UTC, GabrLit commented on src/components/footer/footer.module.scss
> +
be consistent, have blank line between those nested selectors or not

2024-01-29 19:59 UTC, GabrLit commented on src/components/footer/footer.module.scss
> +    line-height: 20px;
this should be probably defined as a mixin in typography, for example:

```ts
@mixin body1--bold {
  font-size: 24px;
  line-height: 32px;
  font-weight: 600;
}
```

see how this font is named in Figma, each one has its own name

2024-02-02 13:44 UTC, closed without merging